sudo: required
services:
  - docker

before_install:
  - docker build -t yourusername/yourimage:$TRAVIS_BUILD_NUMBER .

script:
  - docker run yourusername/yourimage:$TRAVIS_BUILD_NUMBER npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yourusername/yourimage:$TRAVIS_BUILD_NUMBER